config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :transactions
  resources :home
  get '/external_transactions', to: 'transactions#external_transactions'
  devise_for :users
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def created_at
    attributes['created_at'].strftime('%d %b %Y')
  end

  def time_created_at
    attributes['created_at'].strftime('%d %b %Y at %I:%M %P')
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :transactions
  validates :name, presence: true
  has_one_attached :avatar
end

app/models/group_transaction.rb
class GroupTransaction < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_many :groups
  validates :name, :amount, presence: true
  validates :desc, presence: true, length: { maximum: 100 }

  scope :recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :transactions
  has_many :groups

  def external_transaction(tran)
    tran.select { |t| t.group_id.nil? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:avatar, :name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:avatar, :name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @transactions = @group.transactions.includes([:user])
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:avatar, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @transactions = current_user.transactions.all.recent
    @total = current_user.transactions.pluck(:amount).inject(0) { |sum, x| sum + x }
  end

  def show
    Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    @groups = Group.all.collect
  end

  def edit; end

  def create
    @transaction = current_user.transactions.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Your bill was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Your bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Your bill was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def external_transactions
    @all_transactions = current_user.transactions.all.recent
    @e_transactions = current_user.external_transaction(@all_transactions)
    @e_total = current_user.transactions.where(group_id: nil)
    @ex_total = @e_total.pluck(:amount).inject(0) { |sum, x| sum + x }
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :desc, :group_id)
  end
end

app/helpers/application_helper.rb
# rubocop:disable Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity

module ApplicationHelper
  def which_page
    if current_page?(transactions_path)
      content_tag :h3, 'ALL', class: 'font-weight-light mt-2'
    elsif current_page?(external_transactions_path)
      content_tag :h3, 'EXTERNAL', class: 'font-weight-light mt-2'
    elsif current_page?(groups_path)
      content_tag :h3, 'GROUPS', class: 'font-weight-light mt-2'
    elsif current_page?(new_transaction_path)
      content_tag :h3, 'NEW BILL', class: 'font-weight-light mt-2'
    elsif current_page?(edit_user_registration_path)
      content_tag :h3, 'EDIT USER', class: 'font-weight-light mt-2'
    elsif current_page?(new_group_path)
      content_tag :h3, 'NEW GROUP', class: 'font-weight-light mt-2'
    end
  end

  def nav_display
    return unless user_signed_in?
    return unless current_user.avatar.attached?

    if current_page?(home_index_path)
      link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link btn bg-green text-white'
    else
      image_tag current_user.avatar, class: 'rounded-circle'
    end
  end
end

# rubocop:enable Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity

app/helpers/groups_helper.rb
module GroupsHelper
  def group_img(group)
    if group.avatar.attached?
      image_tag group.avatar
    elsif !group.avatar.attached?
      image_tag 'folder.png', alt: 'folders icon'
    end
  end

  def group_img_show
    if @group.avatar.attached?
      image_tag @group.avatar, class: 'mr-2'
    elsif !@group.avatar.attached?
      image_tag 'folder.png', alt: 'folders icon', class: 'mr-2'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def user_avatar
    image_tag current_user.avatar, class: 'rounded-circle' if current_user.avatar.attached?
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/groups/_edit_form.html.erb
<div class="light-font text-dark">
  <%= simple_form_for(@group) do |f| %>
    <div class="form-group mt-4">
      <%= f.input :name, required: true, autofocus: true, class: 'form-control', placeholder: 'Name', label: false %>
    </div>
    <div class="form-group">
      <%= f.file_field :avatar %>
    </div>
    <div class="form-group">
      <%= f.button :submit, 'Update Group', class: 'btn bg-blue w-100 text-white' %>
    </div>
  <% end %>
</div>

app/views/groups/_form.html.erb
<div class="light-font text-dark">
  <%= simple_form_for(@group) do |f| %>
    <div class="form-group mt-4">
      <%= f.input :name, required: true, autofocus: true, class: 'form-control', placeholder: 'Name', label: false %>
    </div>
    <div class="form-group">
      <%= f.file_field :avatar %>
    </div>
    <div class="form-group">
      <%= f.button :submit, 'Create Group', class: 'btn btn-primary w-100' %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<%= render 'edit_form', group: @group %>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-6">
    <%= button_to 'Back', groups_path, method: :get, class: 'btn bg-green p-2 w-100 text-white' %>
  </div>
  <div class="col-6">
    <%= button_to 'Delete', group_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="text-white light-font mt-3 group-index">
  <% @groups.each do |group| %>
    <div class="d-flex animate__animated animate__bounceIn">
      <div class="group-img mr-2 mb-3">
        <%= group_img(group) %>
      </div>
      <div class="d-flex justify-content-between w-100 border-silver border-bottom mb-3">
        <div class="d-flex flex-column justify-content-center">
          <b> <%= group.name %> </b>
          <p class="text-dark"><%= group.created_at %></p>
        </div>
        <div class="d-flex align-items-center mb-3 mr-2">
          <%= link_to group do %>
            <i class="fas fa-sign-in-alt text-green fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="fixed-bottom text-center light-font">
  <%= button_to 'Add New', new_group_path, method: :get, class: 'btn col-11 bg-green p-3 mb-2 text-white' %>
</div>

app/views/groups/new.html.erb
<%= render 'form', group: @group %>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-12">
    <%= button_to 'Back', groups_path, method: :get, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>

app/views/groups/show.html.erb
 <div class="row group-show light-font">
  <div class="group-img d-flex justify-content-center align-items-center total-box p-2 col-12 mb-3">
    <%= group_img_show %>
    <h3 class="text-dark bold-font"> <%= @group.name %> </h3>
  </div>
  <% @transactions.each do |transaction| %>
    <div class="d-flex flex-column p-2 justify-content-between m-auto col-11">
      <%= link_to transaction do %>
      <div class="card w-100">
        <div class="card-body px-0 d-flex">
          <div class="d-flex justify-content-center align-items-center col-3">
            <%= image_tag 'payment.png', alt: 'payment', class: 'trans-img' %>
          </div>
          <div class="d-flex flex-column justify-content-between col-9">
            <div class="d-flex justify-content-between">
              <div class="text-secondary font-weight-light mb-2">
                <%= transaction.name %>
              </div>
              <div>
                <b>£<%= transaction.amount %> </b>
              </div>
            </div>
            <div class="text-secondary font-weight-light d-flex justify-content-between mt-2">
              <div>
                <%= transaction.created_at %>
              </div>
              <div>
                <b class="text-green"> <%= transaction.user.name %> </b>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-6">
    <%= button_to 'Edit', edit_group_path(@group), method: :get, class: 'btn bg-green p-2 text-white w-100' %>
  </div>
  <div class="col-6">
    <%= button_to 'Back', groups_path, method: :get, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div id="main-page" class="row">
    <ul class="nav sessions col-10 text-center text-white light-font">
      <%= user_avatar %>
      <li class="nav-item mt-2 text-dark bold-font">
        <%= current_user.name %>
      </li>
      <li class="nav-item mt-3">
        <%= link_to 'Bills', transactions_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'External Bills', external_transactions_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Groups', groups_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Account', edit_user_registration_path, class: 'nav-link text-white' %>
      </li>
    </ul>
  </div>
<% else %>
  <div class="sessions home-title">
    <h1 class="mb-5">
      FamilyBills
    </h1>
  </div>
  <ul class="nav row text-center fixed-bottom mb-3 m-auto light-font">
    <li class="nav-item col-12">
      <%= link_to "Sign In", new_user_session_path, class: 'nav-link btn bg-green text-white w-100 p-3' %>
    </li>
    <li class="nav-item mt-2 mb-2 col-12">
      <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link btn bg-blue text-white w-100 p-3' %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/867f1dd431.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>
  <body class="container-fluid <%= 'blue-background' if current_page?(groups_path) || current_page?(home_index_path) || current_page?(root_path) && user_signed_in? %>">
    <div class="row">
      <% if flash[:notice] %>
        <div class="bg-success col-12 text-center p-2">
          <p class="notice text-white m-auto"> <%= notice %> </p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="bg-danger col-12 text-center p-2">
          <p class="alert text-white m-auto"> <%= alert %> </p>
        </div>
      <% end %>
    </div>
    <div class="row">
      <nav class="bg-blue navbar col-12 main-navbar <%= 'd-none' if !user_signed_in? %>">
        <ul class="nav <%= 'd-none' if current_page?(home_index_path) %>">
          <%= link_to home_index_path, class: "nav-item" do %>
            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="2em" height="2em" viewBox="0 0 124 124" fill="#fff" style="enable-background:new 0 0 124 124;" xml:space="preserve">
              <g>
                <path d="M112,6H12C5.4,6,0,11.4,0,18s5.4,12,12,12h100c6.6,0,12-5.4,12-12S118.6,6,112,6z"/>
                <path d="M112,50H12C5.4,50,0,55.4,0,62c0,6.6,5.4,12,12,12h100c6.6,0,12-5.4,12-12C124,55.4,118.6,50,112,50z"/>
                <path d="M112,94H12c-6.6,0-12,5.4-12,12s5.4,12,12,12h100c6.6,0,12-5.4,12-12S118.6,94,112,94z"/>
              </g>
            </svg>
          <% end %>
        </ul>
        <ul class="nav text-white justify-content-center bold-font">
          <%= which_page %>
        </ul>
        <ul class="nav nav-img light-font">
          <%= nav_display %>
        </ul>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/transactions/_edit_form.html.erb
<div class="light-font text-dark">
  <%= form_with(model: transaction, local: true) do |form| %>
  <div class="form-group mt-4">
    <%= form.text_field :name, class: 'form-control', autofocus: true, placeholder: 'Name', required: true %>
  </div>

  <div class="form-group">
    <%= form.number_field :amount, class: 'form-control', step: :any, placeholder: 'Amount', required: true %>
  </div>

  <div class="form-group">
    <%= form.text_area :desc, class: 'form-control', step: :any, placeholder: 'Description', required: false %>
  </div>

    <div class="form-group">
      <%= form.collection_select(:group_id, Group.all, :id, :name, prompt: "select group", multiple: true, required: false) %>
    </div>
  
  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary w-100' %>
  </div>
<% end %>
</div>

app/views/transactions/_ex-transactions.html.erb
<div class="row trans-index light-font">
  <div class="d-flex justify-content-between total-box col-12 p-3 mb-3">
    <div>
      Total
    </div>
    <div>
      <b class="text-green bold-font">£<%= @ex_total %> </b>
    </div>
  </div>
  <% @e_transactions.each do |transaction| %>
    <div class="d-flex flex-column p-2 justify-content-between m-auto col-11">
      <div class="card w-100 animate__animated animate__bounceIn">
        <div class="card-body px-0 d-flex">
          <div class="d-flex justify-content-center align-items-center col-3">
            <%= image_tag 'payment.png', alt: 'payment', class: 'trans-img' %>
          </div>
          <div class="d-flex flex-column justify-content-between col-9">
            <div class="d-flex justify-content-between">
              <div class="text-secondary font-weight-light mb-2">
                <%= transaction.name %>
              </div>
              <div>
                <b>£<%= transaction.amount %> </b>
              </div>
            </div>
            <div class="text-secondary font-weight-light d-flex justify-content-between mt-2">
              <div>
                <%= transaction.created_at %>
              </div>
              <div>
                <%= link_to transaction do %>
                  <i class="fas fa-info-circle mr-1 trans-icons text-blue"></i>
                <% end %>
                <%= link_to transaction, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-trash-alt ml-1 trans-icons text-blue"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="fixed-bottom text-center light-font">
  <%= button_to 'Add New', new_transaction_path, method: :get, class: 'btn col-11 bg-green p-3 mb-2 text-white' %>
</div>

app/views/transactions/_form.html.erb
<div class="light-font text-dark">
  <%= form_with(model: transaction, local: true) do |form| %>
  <div class="form-group mt-4">
    <%= form.text_field :name, class: 'form-control', autofocus: true, placeholder: 'Name', required: true %>
  </div>

  <div class="form-group">
    <%= form.number_field :amount, class: 'form-control', step: :any, placeholder: 'Amount', required: true %>
  </div>

  <div class="form-group">
    <%= form.text_area :desc, class: 'form-control', step: :any, placeholder: 'Description', required: true %>
  </div>

    <div class="form-group">
      <%= form.collection_select(:group_id, Group.all, :id, :name, prompt: "select group", multiple: true, required: false) %>
    </div>
  
  <div class="form-group">
    <%= form.submit 'Create Bill', class: 'btn btn-primary w-100' %>
  </div>
<% end %>
</div>

app/views/transactions/edit.html.erb
<%= render 'edit_form', transaction: @transaction %>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-12">
    <%= button_to 'Back', transaction_path, method: :get, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>

app/views/transactions/external_transactions.html.erb
<%= render 'ex-transactions' %>

app/views/transactions/index.html.erb
<div class="row trans-index light-font">
  <div class="d-flex justify-content-between total-box col-12 p-3 mb-3">
    <div>
      Total
    </div>
    <div class="total-num text-green bold-font">
       <b>£<%= @total %> </b>
    </div>
  </div>
  <% @transactions.each do |transaction| %>
    <div class="d-flex flex-column p-2 justify-content-between m-auto col-11">
      <div class="card w-100 animate__animated animate__bounceIn">
        <div class="card-body px-0 d-flex">
          <div class="d-flex justify-content-center align-items-center col-3">
            <%= image_tag 'payment.png', alt: 'payment', class: 'trans-img' %>
          </div>
          <div class="d-flex flex-column justify-content-between col-9">
            <div class="d-flex justify-content-between">
              <div class="text-secondary font-weight-light mb-2">
                <%= transaction.name %>
              </div>
              <div>
                <b>£<%= transaction.amount %> </b>
              </div>
            </div>
            <div class="text-secondary font-weight-light d-flex justify-content-between mt-2">
              <div>
                <%= transaction.created_at %>
              </div>
              <div>
                <%= link_to transaction do %>
                  <i class="fas fa-info-circle mr-1 trans-icons text-blue"></i>
                <% end %>
                <%= link_to transaction, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-trash-alt ml-1 trans-icons text-blue"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="fixed-bottom text-center light-font">
  <%= button_to 'Add New', new_transaction_path, method: :get, class: 'btn col-11 bg-green p-3 mb-2 text-white' %>
</div>

app/views/transactions/new.html.erb
<%= render 'form', transaction: @transaction %>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-12">
    <%= button_to 'Back', transactions_path, method: :get, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="row mt-4 light-font text-dark">
  <div class="card m-auto col-11 text-start">
  <div class="card-body">
    <div class="d-flex align-items-center bold-font">
    <%= image_tag 'payment.png', alt: 'payment', class: 'trans-img mr-2' %>
    <%= @transaction.name %>
  </div>
     <p class="card-text mt-3">
      <%= @transaction.desc %>
    </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item text-muted">
     <i class="far fa-calendar mr-1"></i> <%= @transaction.time_created_at %>
    </li>
  </ul>
  <div class="card-body d-flex justify-content-between">
    <div>
      TOTAL PAYMENT
    </div>
    <div class="bold-font">
      £<%= @transaction.amount %>
    </div>
  </div>
</div>
</div>

<div class="fixed-bottom text-center d-flex row m-2 light-font">
  <div class="col-6">
    <%= button_to 'Edit', edit_transaction_path(@transaction), method: :get, class: 'btn bg-green p-2 text-white w-100' %>
  </div>
  <div class="col-6">
    <%= button_to 'Back', transactions_path, method: :get, class: 'btn bg-danger p-2 w-100 text-white' %>
  </div>
</div>